"""Add season columns

Revision ID: 1aaee5a9547e
Revises: a41325ad3924
Create Date: 2026-06-28 00:19:27.006598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaee5a9547e'
down_revision: Union[str, Sequence[str], None] = 'a41325ad3924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('season', sa.String(), nullable=True))
    op.add_column('games', sa.Column('season_type', sa.String(), nullable=True))
    op.add_column('games', sa.Column('game_date', sa.String(), nullable=True))
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_season_type'), 'games', ['season_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_season_type'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_column('games', 'game_date')
    op.drop_column('games', 'season_type')
    op.drop_column('games', 'season')
    # ### end Alembic commands ###
