"""Initial migration

Revision ID: a41325ad3924
Revises: 
Create Date: 2026-06-25 22:59:49.737222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41325ad3924'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tricode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_tricode'), 'teams', ['tricode'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.String(), nullable=True),
    sa.Column('away_team_id', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_win', sa.Boolean(), nullable=True),
    sa.Column('total_plays', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('action_number', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('clock', sa.String(), nullable=True),
    sa.Column('seconds_remaining', sa.Float(), nullable=True),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('score_diff', sa.Integer(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_tricode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_tricode'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
